export const SET_PRODUCTS = "SET_PRODUCTS"
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART'
export const ADD_PRODUCT_WISHLIST = 'ADD_PRODUCT_WISHLIST'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'